### ISSUE TITLE
release engineering 3.7.0

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#1012]
let's have another MirageOS release. My main motivation is to push through #1004 (but also have a decent solution to the hooks, i.e. #1010). Release schedule is tentative this week (e.g. before Nov 5th)!

issues and PRs to be addressed / merged
- [ ] #1004 (drop lwt.t and cstruct.t abstraction from interfaces -- certainly requires sth like #1006)
- [x] #1010 (add hook to mirage-runtime)
- [x] #1011 (exit 0)
- [x] #1008 (mirage configure to delete opam files) -- needs code and a PR
- [x] #1003 (use Stdlib instead of Pervasives)
- [x] #952 (since #1004 requires updated to all implementations anyways)

mirage-os-shim affected changes (#1010)
- [x] mirage-runtime 3.7.0 release ocaml/opam-repository#15163
- [x] mirage/mirage-entropy#45 mirage/mirage-entropy#46 v0.5.0 ocaml/opam-repository#15173
- [x] mirage/mirage-unix#14 mirage/mirage-unix#15 v4.0.0 ocaml/opam-repository#15170
- [x] mirage/mirage-solo5#54 mirage/mirage-solo5#55 v0.6.1 ocaml/opam-repository#15186
- [x] mirage/mirage-xen#20 (revert) mirage/mirage-xen#21 v5.0.0 ocaml/opam-repository#15168

~~in respect to #1004, here's a list of PRs that needs to be merged and released (TODO: still some are missing, most notably dns, conduit, cohttp, irmin, git)~~ all PRed now!

libraries I won't manage to include (help is welcome!) -- since they're not required by mirage (or mirage-skeleton), they can be released after the mirageos release
- capnp-rpc
- dns-forward
- nbd
- qcow
- hvsock
- datakit
- protocol-9p
- vpnkit

PRs
- [x] mirage/mirage-net-solo5#35 v0.6.1 ocaml/opam-repository#15174
- [x] mirage/mirage-net-unix#48 v2.7.0 ocaml/opam-repository#15151
- [x] mirage/mirage-net-xen#95 v1.13.0 ocaml/opam-repository#15178
- [x] mirage/mirage-vnetif#28 v0.5.0 ocaml/opam-repository#15142
- [x] mirage/mirage-net-macosx#37 v1.8.0 ocaml/opam-repository#15190
- [x] mirage/ethernet#6 v2.2.0 ocaml/opam-repository#15144
- [x] mirage/arp#17 v2.2.0 ocaml/opam-repository#15146
- [x] mirage/mirage-tcpip#420 v4.0.0 ocaml/opam-repository#15162
- [x] mirage/charrua#105 v1.2.0 ocaml/opam-repository#15169
- [x] mirage/mirage-block-solo5#19 v0.6.1 ocaml/opam-repository#15175
- [x] mirage/mirage-block-unix#99 v2.12.0 ocaml/opam-repository#15148
- [x] mirage/mirage-block-xen#86 v1.7.0 ocaml/opam-repository#15179
- [ ] mirage/mirage-block-ramdisk#20
- [ ] mirage/ocaml-fat#83
- [ ] mirage/ocaml-tar#73
- [x] mirage/mirage-random-test#2 v0.1.0 ocaml/opam-repository#15144
- [x] mirage/mirage-random-stdlib#3 v0.1.0 ocaml/opam-repository#15145
- [x] mirage/mirage-fs-unix#47 v1.7.0 ocaml/opam-repository#15149
- [x] mirage/mirage-kv-mem#3 v3.0.0 ocaml/opam-repository#15147
- [x] mirage/mirage-kv-unix#2 v2.1.0 ocaml/opam-repository#15150
- [x] mirage/ocaml-crunch#50 v3.1.0 ocaml/opam-repository#15164
- [x] mirleft/ocaml-tls#401 v0.10.5 ocaml/opam-repository#15171
- [x] mirage/mirage-console-solo5#19 v0.6.1 ocaml/opam-repository#15176
- [x] mirage/ocaml-vchan#134 v5.0.0 ocaml/opam-repository#15180
- [x] mirage/mirage-logs#17 v1.2.0 ocaml/opam-repository#15165
- [x] mirage/mirage-bootvar-xen#43 mirage/mirage-bootvar-xen#42 v0.7.0 ocaml/opam-repository#15181
- [x] mirage/mirage-qubes#46 v0.8.0 ocaml/opam-repository#15189
- [x] mirage/mirage-console#82 v3.0.1 ocaml/opam-repository#15182
- [x] mirage/ocaml-dns#196 v4.1.0 ocaml/opam-repository#15177
- [x] mirage/ocaml-conduit#306 v2.0.2 ocaml/opam-repository#15188
- [ ] mirage/ocaml-cohttp#678 (needs conduit)
- [ ] mirage/ocaml-git#376 (needs cohttp conduit)
- [ ] mirage/irmin#883 (needs git)
- [x] nocrypto 0.5.4-2 (build mirage support if mirage-entropy is present) https://github.com/ocaml/opam-repository/pull/15192
- [x] functoria 3.0.2 (avoid version parsing to allow constraints of 0.5.4-2) https://github.com/ocaml/opam-repository/pull/15197

anything else we should include in the release? it'll be mostly compatible with 3.6.0 (mirage-types & mirage-types-lwt are only deprecated but still around, same should be for the hooks registration in the backends) -- we can remove the deprecated things with mirage 4.0

notably other changes:
- cstruct lower bound is now at 4.0.0
- lwt lower bound is at 4.0.0 (EDIT: I PRed changes to lower it from 4.4.0 to 4.0.0)
- OCaml lower bound is at 4.6.0 (finally, safe-string for everyone)

**Comment by mato** [comment]
> anything else we should include in the release?

From https://github.com/mirage/mirage-os-shim/pull/7#issuecomment-543154642: I'd like to have a way for applications (e.g. Canopy) depending on packages that make use of variants (e.g. digestif, checkseum) to build out of the box with the ocamlbuild-based Mirage 3.7.0.

We could:

1. do nothing and document/use the `_tags` approach suggested by @dinosaure in https://github.com/Engil/Canopy/pull/95#issuecomment-543729138, if this is sufficient for all cases?

2. or, as I discussed with @hannesm yesterday, it may be worth investigating if we can use OPAM per-package variables (or other metadata) to provide information about default variants to the mirage tool so that it could generate / pass this to ocamlbuild. WDYT?

**Comment by dinosaure** [comment]
> From mirage/mirage-os-shim#7 (comment): I'd like to have a way for applications (e.g. Canopy) depending on packages that make use of variants (e.g. digestif, checkseum) to build out of the box with the ocamlbuild-based Mirage 3.7.0.

For this specific point, the current problem is the orchestration of the build-system to choose which implementation we want to use at the end. As far as I can know, only `dune` provides a mechanism (a _default_ implementation) which is chosen at the end and avoid a non-expecting linking-error.

 `META` file/`ocamlfind` and `ocamlbuild` is not able to do that and we still need to explicitly choose the implementation with the `_tags` file (the more easy way).

The proposal on mirage/mirage-os-shim#7 use the `dune` feature for that and mirage/mirage-os-shim#8 follows the same distribution pattern without `dune`. Then, the mirage tool must be updated to orchestrate by itself (mirage/mirage#1005) or by something else (`mirage` + `dune` + `duniverse`) to choose the right implementation.

According the current status of MirageOS (`ocamlbuild`), I did not (yet!) find a proper way to automatize that, plenty of solution exist (`dune`/`duniverse`/`OPAM`) but we need to find a right one.

As I said into mirage/mirage-os-shim#7, `virtual_library`/`variant`/`linking_trick` is really interesting but it is little bit far for us and will surely overlap the _dunification_ of MirageOS. To avoid a complexity and keep small changes for the _dunification_ purpose, I really would like to post-pone that.

**Comment by hannesm** [comment]
I created an opam overlay https://github.com/hannesm/mirage-dev/tree/easy which is able to build mirage-skeleton (apart from examples requiring conduit-mirage, to be fixed soon). I also started releases to opam-repository (see above checklist for the current state), and will work on more in the following evenings.

**Comment by dinosaure** [comment]
I just would like to clear a situation into `mirage/mirage`. Currently, by the choice made into #1010, the _linking-trick_ does not exist anymore for `nocrypto`. As I explained into several issues, `nocrypto` uses an unusual way to check that the `entropy` engine is properly loaded:

https://github.com/mirage/mirage/blob/master/lib/mirage.ml#L847

May be we should, for the release of MirageOS 3.7, try to see if we can delete it.

**Comment by hannesm** [comment]
@mato I'd be open to something along those lines, but don't know how to figure out the "default variant"

@dinosaure ok, that would be nice to have removed, but how? (i.e. i still think that code is useful, but am happy to be convinced that it is not needed anymore) -- AFAIU mirage needs to emit the `Nocrypto_entropy_mirage.connect ()` call, which is only done if the `nocrypto` device is in the functoria dependency graph (either explicit, as the message you point to suggests, by adding `abstract nocrypto` to dependencies -- or implicit by using the `nocrypto_random`). But: if you use the `stdlib_random` as random device and also depend on nocrypto/tls, nocrypto's fortuna won't get seeded unless you add the dependency manually (and nocrypto uses its own Rng directly, not the mirageos selected one (which makes sense for a crypto library to have a decent rng)). To me it feels a bit scary to have stdlib_random and nocrypto in the same unikernel, I'd be in favour of avoiding this.

**Comment by dinosaure** [comment]
> To me it feels a bit scary to have stdlib_random and nocrypto in the same unikernel, I'd be in favour of avoiding this.

A possible hard solution should be to add a conflict in OPAM between `mirage-random-stdlib` and `nocrypto`. Generated OPAM file by `mirage` will go wrong and imply the user to use the `nocrypto` entropy engine xor `mirage-random-stdlib`. However, even if the solution is possible, I'm not really convince by that.

**Comment by hannesm** [comment]
NOTE: from a user perspective it may have been better if e.g. mirage-time 2.0.0 would provide a Mirage_time_lwt (containing `[@@@deprecated] include Mirage_time`) -- this way existing unikernels would still compile (with deprecation warnings). this could be retro-fitted by drafting interface releases (though I'm pretty busy this week). removal could then be in the next major (mirageos) version.

**Comment by mato** [comment]
@hannesm Is this release 3.7.1 or 3.7.0? Your mailing list announcement says 3.7 and 3.7.1. Also, given that this has breaking changes, it would be good to announce also on https://mirage.io/ and https://discuss.ocaml.org/.

**Comment by hannesm** [comment]
> release 3.7.1 or 3.7.0? Your mailing list announcement says 3.7 and 3.7.1

both. the mirage/mirage repository contains 4 opam packages (mirage, mirage-types, mirage-types-lwt, mirage-runtime) -- 3.7.0 was only a mirage-runtiime release to be able to release mirage-solo5, mirage-xen, mirage-entropy, mirage-unix which depend on mirage-runtime >= 3.7.0.

> Also, given that this has breaking changes, it would be good to announce also on https://mirage.io/ and https://discuss.ocaml.org/.

The amount of breaking changes is what caught my attention as well, and this morning I figured out a solution. I went through the interface packages and implemented (and deprecated) `Mirage_x_lwt` modules, each of which contains only `include Mirage_x`. CI build it (including reverse dependencies), and there's a set of releases to opam-repository which as well removes the earlier releases (without the compatibility module):
- mirage-net https://github.com/ocaml/opam-repository/pull/15211
- mirage-time https://github.com/ocaml/opam-repository/pull/15212
- mirage-block https://github.com/ocaml/opam-repository/pull/15213
- mirage-fs https://github.com/ocaml/opam-repository/pull/15214
- mirage-kv https://github.com/ocaml/opam-repository/pull/15216
- mirage-console https://github.com/ocaml/opam-repository/pull/15217
- mirage-flow https://github.com/ocaml/opam-repository/pull/15218
- mirage-protocols https://github.com/ocaml/opam-repository/pull/15219
- mirage-stack https://github.com/ocaml/opam-repository/pull/15220
- mirage-channel https://github.com/ocaml/opam-repository/pull/15221
- mirage-clock https://github.com/ocaml/opam-repository/pull/15212

once these are merged, the current mirage-skeleton master (without merging the above mentioned PR) builds with both mirage 3.6.0 and 3.7.1. I'll then follow up on the mailing list and announce to discourse, and prepare a PR to mirage-www.

Sorry for the hickup and for a period of ~30 hours with a big breaking changes fallout. I learned from it :)

**Comment by mato** [comment]
Thanks. This is a good solution.
