### ISSUE TITLE
1.0 Release checklist

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#102]
# Usecases:
- Decks.OpenMirage.org
- WWW.OpenMirage.org (Xen mode, content served from a block device)
- WWW.OpenMirage.org (Crunched)
- Personal home pages for: @samoht @mor1 @djs55 @amirmc @jonludlam 
- [x] Move repo to mirage org to keep history (@avsm)
- [x] Merge mirage repo with mirage-platform master (@avsm)
- [x] Blog post about OSCon (@mor1)
- [x] Fix mirage-skeleton and make root Makefile build everything (@djs55)
- [x] Populate xen.org wiki (@djs55)
- [x] Quick RT script (@avsm)
- [x] Vchan blog post (@vbmithr)
- [x] Link all the videos and blogs to mirage-www (@avsm)
- [x] Configure Bytemark Xen machines (@djs55)
- [x] Sanitize installation instructions (@mor1) -- will be checked by Prashanth and Chris.
- [x] fix event race in activations.wait (@djs55 / @avsm )

DP2
- [ ] Try the new ocamldoc to build a trove (@avsm)
- [ ] OPAM 1.1 testing (@samoht)  _the week after_
- [x] XenSummit storage submission (@djs55)  _august end_
- [ ] Multiple website + load balancer _when it works_
- [ ] Breaking up mirage-net
- [ ] Github trove? (@avsm)
- [ ] Load testing
- [ ] Openflow status
- [x] Fix Mirari on Unix (@avsm)
- [ ] Add combinator interface to Mirari instead of concrete syntax (@avsm) 
- [x] Travis tests
- [ ] Self-updating website via Travis
- [ ] Port mirage-www to cowabloga (@avsm)
