### ISSUE TITLE
Libraries for 1.0 checklist

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#111]
(extracted from #102, running parallel to #109)
## Core Unix/Xen libraries:
- [ ] **shared-memory-ring**: Builds shared memory-based point-to-point communication protocols. Is reasonably mature and can be released. Can be used outside of Xen, need to benchmark vs c. 4.01.0dev ocaml improves perf with bigarray builtins. Implements the Xen ABI, but needs examples in-tree. (@djs55). For 1.0.
- [ ] **ocaml-xenstore**: Repo layout is confusing. Client and server in here, as well as Lwt bindings. Does build as stub domain and unix kernel. How can this stay in sync with xen-unstable? (@djs55). For 1.0.
- [ ] **ocaml-fd-send-recv**: UNIX only and trivial. Released and stable. For 1.0. (@djs55/@vbmithr)
- [ ] **ocaml-xen-block-driver**: Successfully moved out, and works in Xen. It once worked in userspace. (@djs55 / @jonludlam). For 1.0.
- [x] **ocaml-cstruct**:

POST 1.0:
- [ ] **ocaml-vchan**: Vchan communication channel between VMs. Provides a socket-like interface between VMs. For 1.0 (Owner: @djs55). Post 2.0: vsock?
- [ ] **ocaml-qmp**: QEMU message-passing protocol to command a running qemu. Not for 1.0, really for advanced use (@djs55 ).
- [ ] **ocaml-gntshare**: Interface to mapping pages across Xen VMs. In ocaml-xen-lowlevel-libs, in good state, part of upstream xen-unstable and needs synching. (@djs55)
- [ ] **ocaml-xen-net-driver**: Can be moved out, and works in Xen. It once worked in userspace. (@djs55 / @jonludlam). For 1.1.
## Core Mirage libraries and tools:
- [x] **mirage-platform**:
- [x] **mirari**:
- [x] **opam**:

POST 1.0:
- [ ] **dyntype**: 
- [x] **ocaml-re**: stable, done
- [ ] **cross-ref ocamldoc**: leo
## Storage libraries:
- [x] **ocaml-fat**: 
- [x] **mirage-fs**: Just there for crunch. Probably not needed.
- [x] **ocaml-crunch**: Works.

POST 1.0:
- [ ] **libvhd**: ?? Jon, suitable for block driver use?
- [ ] **ocaml-iscsi**: Doesnt exist, but djs really wants it.
- [ ] **cagit**: Needs a file system (Owner: tg).
- [ ] **irminsule**: tg, not for 1.0
- [ ] **arakoon**: In-memory-only patch, Arakoon already functorised across the storage layer. For 1.0? to investigate
- [ ] **orm**: Post 1.0, needs sqlite bindings
## Network libraries
- [x] **ocaml-tuntap** 
- [x] **mirage-net**  - with a ping test?

POST 1.0:
- better abstraction for mirage-net
- [ ] **ocaml-dns**:
- [ ] **ocaml-pcap**:
- [ ] **ocaml-openflow**:
- [ ] **ocaml-xmpp**: ermine repos, lwt, need porting to mirage-net
## RPC/coordination:

POST 1.0:
- [ ] **rpc-light**: Works well, but slow and no wire protocol defined. Vb mentioned Thrift. Also have bin_io? No versioning story. Needs obuild help. (Owner: tg)
- [ ] **message-switch**:
- [ ] **ocamlmq**: to investigate.
- [ ] **logger**: need a vchan-based logger and CLI to access from other domain
## Security:

POST 1.0:
- [ ] **mirage-cryptokit**:
- [ ] **ocaml-crypto-keys**:
- [ ] **stud**: need ssl binding for fable
- [ ] **ocaml-ssh**: still in mpl-land, not too hard to port
## Webby libraries:
- [x] **ocaml-cohttp**:
- [x] **ocaml-cow**:
- [ ] **ocaml-atom**:
- [ ] **ocaml-cowabloga**:
- [x] **ocaml-uri**:

POST 1.0:
- [ ] **ocaml-spdy**: out of date, not for 1.0
## Cloud interfaces:
- [ ] **aws**: ec2 bindings, just a shell script should be sufficient.
- xref to OSv docs on this?

POST 1.0:
- [ ] **ocaml-libvirt**: dave upstreaming
- [ ] **xenopsd**: convenient single-host daemon for ubuntu-unstable.
## Testing:

POST 1.0:
- [ ] **Ocamlot**
- [ ] **Pathos testing**?
## Tutorials and examples:
- [x] **mirage-skeleton**: important for regress tests.
- [x] **mirage-www**
## Misc
- [ ] **Integrate ocaml-tuntap** into mirage-platform to remove tun hacks [vincent]

POST 1.0:
- [ ] **cohttp/ssl** releases [anil]
