### ISSUE TITLE
mirage 4.0 tracking issue

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#1217]
From Mirage dev meeting. This will be edited as we converge on release criteria:

Release criteria:
- Self hosted infrastructure using the new trees running live (e.g. website and DNS) as a fitness test
- Tooling based on the recommended OCaml Platform tools (e.g. opam, dune, merlin and so on)

Items remaining:
- [x] mirage tool PRs
- [x] mirage-www branch to use mirage 4

opam-monorepo release (lucas talked with nathan):
- [x] pin-depends still missing
- [x] 4.12 PR is around
- [ ] offline mode https://github.com/ocamllabs/opam-monorepo/issues/213

upstreaming duniverse forks:
- [x] solo5 merge
- [x] ocaml-freestanding merge
- [x] Zarith to the duniverse
- [x] gmp freestanding to the duniverse
- [x] dbuenzli's library overlays
- [x] irmin-watcher still using jbuilder
- [x] inotify (irmin-watcher depends on that) still uses ocamlbuild
- [x] tcpip C stubs https://github.com/mirage/mirage-tcpip/pull/441
- [x] base/parsexp
- [x] re-evaluate both https://github.com/mirage/mirage-dev/tree/mirage-4/packages and https://github.com/dune-universe/opam-overlays/tree/master/packages for what can be upstreamed
- [x] should mirage4 (the tool) use a custom branch (or a fork) of dune-universe/opam-overlays (to avoid conflicts of other users of that repository)? -> no, maintain opam-overlays
- [x] evaluate our previous roadmap https://github.com/mirage/mirage/issues/994
- [x] evaluate / close https://github.com/mirage/mirage/issues/1195
- [x] how mirage4 will achieve cross-compilation? (documentation -- the mirage tool will be able to achieve this)
- [x] `io-page` - https://github.com/ocaml/opam-repository/pull/18379
- [x] upgrade mirage-skeleton & others unikernels with the new version of `functoria` (objects to modules)

CI system:
- [x] deploy ci.mirage.io with the new workflow
  * [x] promote CI to infrastructure managed on ocurrent-deployer 
- [x] document the new workflow on mirage.io
- [ ] docs generation in ocurrent to replace docs.mirage.io
  *  [ ] promote docs gen to infra managed on ocurrent-deployer
- [x] modify ocluster-deployer to roll out mirage-4-based site

Keeping mirage3 running in LTS mode:
- [ ] nitrokey is one deployment that needs to migrate systematically
- [ ] keep a mirage-www running on mirage3 (load balancer?)

**Comment by avsm** [comment]
dev meeting: authoritative source of dune packages remaining to be upstreamed are now in https://github.com/mirage/mirage-dev/tree/mirage-4 (from the table in #1195)

**Comment by dinosaure** [comment]
To help to centralize PRs:
- `mirage/mirage`, see https://github.com/mirage/mirage/pull/1226
- `ocaml-freestanding`, see https://github.com/mirage/ocaml-freestanding/pull/92
- `Solo5`, see https://github.com/Solo5/solo5/pull/494

Include `mirage-dev` & `opam-overlays` + remaining PR on `opam monorepo`, we have MirageOS 4.

**Comment by dinosaure** [comment]
Some news about the release and what we still need to do.
1) The release of Solo5/`ocaml-freestanding` (see PRs above) is needed. However a question remains, I will try to share my discussion with Martin and @TheLortex about the compatibility with MirageOS 3 and `pkg-config`.

Currently, we are able to keep the compatibility with MirageOS 3 and MirageOS 4. The idea is to keep `pkg-config` in our stack to keep a long-term support. However, Martin explained to me that `pkg-config` should be set only on `ocaml-freestanding`. By this way, we are able to remove `pkg-config` from Solo5.

@TheLortex did something about the MirageOS 3 compatibility with these commits:
TheLortex/Solo5@77db27433ccd5b1ec13735e8ef1c92e141969a5c
TheLortex/Solo5@43cc33d5fbd780abe7f9125b7126fa3957f06c9a
TheLortex/Solo5@07ee8f561ce4b9057a91f42029f091f05a6c53f7

Which are on the top of Solo5/solo5#494. An other solution proposed by Martin is to delete `pkg-config` from Solo5, keep it on the `ocaml-freestanding` layer and make a simple program into Solo5 which can pass CFLAGS/LDFLAGS to `ocaml-freestanding` (and, then, to `pkg-config` - to keep the MirageOS 3 compatibility).

We should decide what we want to do at this stage:
- delete `pkg-config` (and drop the support of MirageOS 3)
- keep it on the `ocaml-freestanding` layer (which is, IHMO, the nicer solution)
- integrate @TheLortex's patches into the Solo5 release to keep the compatibility

2) #1203 (thanks a lot @hannesm) is ready to be closed as soon as we can.
3) @samoht wants to integrate [`mirage-dev`][] packages into [`duniverse/opam-overlays`][] packages with a suffix `+mirage`. We should do that on `base`, `parsexp` and `Zarith`. I think the rest of these packages are in our ownership - so we just need to make a normal release into `opam-repository`
4) Finally, as far as I can say, documents and articles are mostly ready for an announcement.

With all of that, I think we are really ready to make a release.

[`mirage-dev`]: https://github.com/mirage/mirage-dev
[`duniverse/opam-overlays`]: https://github.com/dune-universe/opam-overlays

**Comment by hannesm** [comment]
Thanks for your explanation. I'm pretty undecided about the whole MirageOS 3.x compatibility story. The main issue is: with MirageOS 4, we don't need to add extra Makefiles and sublibraries and META.templates for the freestanding compilation (that are only used if the optional dependency ocaml-freestanding is installed), i.e. getting rid of these would make certain packages easier.

On the same topic, IIUC mirage-solo5 and mirage-xen in the MirageOS 4 world will only be used in the monorepo (and not in the switch), which again allows us to simplify the build system (currently a Makefile for the bindings). Taking this into consideration, while there may be the same source tarball used with MirageOS 3.x and MirageOS 4, the build system will be different --> there is maintenance overhead involved (and that's only worth if we keep MirageOS 3.x CI systems around).

OTOH, if the solution "keep pkg-config on ocaml-freestanding layer" is easy, then let's do that and keep that compatibility around for a year.

Could you elaborate on "documents and articles are mostly ready"? I saw some time ago a release announcement, is there more planned?

**Comment by dinosaure** [comment]
> Could you elaborate on "documents and articles are mostly ready"? I saw some time ago a release announcement, is there more planned?

So may be @samoht and @TheLortex have more outputs than me but it seems that:
- the documentation about cross-compilation is done
- a release candidate was written
- the part about emails was written too
- may be something about `ocurrent`/`albatross` is missing - but I'm not sure that someone wants to write something about that

**Comment by hannesm** [comment]
Discussion from today:
- we remove compatibility (of mirage-solo5 etc.) with MirageOS3 (and thus can remove the cross-compilation Makefile etc.) -- this also allows future changes (such as putting all mirage-net-* implementations into a mirage-net repository and using dune to decide which implementation to use) and MirageOS5 (the effects) work (with the goal to have fewer repositories)
- this will make e.g. mirage-solo5 not installable and testable via opam --> we install mirage-ci there, and can put releases into mirage/opam-overlays (also with mirage-ci installed there) -- alternatively use dune-universe/opam-overlays (?) [I'm still unsure who is maintaining that and what the goals thereof are - and whether e.g. putting mirage-solo5 releases there is sensible]

does that sound right? sorry if I misunderstood or misinterpreted anything.

**Comment by dinosaure** [comment]
Most of the tasks here are closed and done. To avoid a multiplication of places where we talk about MirageOS 4.0, I will close this issue but feel free to fill #1261
