### ISSUE TITLE
mirage.4.0.0-beta tracking issue

### ISSUE THREAD

**Issue by samoht** [mirage/mirage#1261]
This issues tracks the remaining tasks needed to release mirage.4.0.0-beta to opam:
- [x] release ocaml-freestanding.0.7.0 to opam https://github.com/ocaml/opam-repository/pull/20366
- [x] move parsexp and zarith into mirage/opam-overlay: https://github.com/mirage/opam-overlays/pull/8
- [x] rename the OS module to be target specific and release release mirage-{solo5,xen} on opam-repository to be able to generate documentation.
- [x] release functoria and mirage 4.0.0-beta to opam
- [x] switch next.mirage.io to mirage.io
- [x] post the announcement on discuss

**Comment by dinosaure** [comment]
>  rename the OS module to be target specific

I would like to add the ability to release `mirage-{solo5,xen}` on `opam-repository` to be able to generate documentation.

**Comment by hannesm** [comment]
about mirage-solo5 and mirage-xen: could someone open PRs on the respective repositories? I'm indeed in favour (after our discussion) to have them released to opam-repository (for doc builds, and being able to build the OCaml code -- to also have the CI systems enabled).

I guess mirage-net-solo5 and other reverse dependencies "only" need to have their upper bounds for mirage-solo5 adjusted!?

**Comment by hannesm** [comment]
related is #1254 (for the mirage tool) and maybe worth to look into the Mirage 4.0 milestone https://github.com/mirage/mirage/milestone/10

**Comment by dinosaure** [comment]
> rename the OS module to be target specific and release release mirage-{solo5,xen} on opam-repository to be able to generate documentation.

Partially done on #1269 - we need to upgrade `mirage-{xen,solo5,unix}` in consequence.
