### ISSUE TITLE
Few new devices and & gilbraltar support

### ISSUE THREAD

**Issue by dinosaure** [mirage/mirage#1281]
It will be nice to definitely solve some user's experience issues about some unikernels:
- [x] release `git` (see https://github.com/ocaml/opam-repository/pull/20621#issuecomment-1027857508)
- [x] release `docteur`
- [x] fix on the good way `ocaml-ci` about `opam.2.1` (/cc @talex5 @samoht) (see ocurrent/ocaml-ci#412)
- [x] `mirage-crypto-rng-mirage` (see mirage/mirage-crypto#151)
- [x] `vchan-xen` (see mirage/ocaml-vchan#138)
- [x] release of Solo5.0.7.1 (which fix minor bugs)
- [ ] fix `bootvar` for all targets (see mirage/mirage-bootvar-unix#2 & #1248)
- [x] implement `dns` devices
- [x] implement `happy-eyeballs` devices
- [x] implement `mimic` device (see #1283)
- [x] implement `git` device (via TCP/IP, HTTP(S) or SSH) (see #1283)
- [ ] implement `paf` device (to finally support `http/af`, `h2` as possible HTTP clients)
- [ ] upgrade unikernels with MirageOS 4.0.0~beta3
  * [x] `dns-primary-git`
  * [ ] `dns-secondary-letsencrypt`
  * [x] `unipi`
  * [x] `pasteur`
  * [ ] `ptt`
  * [ ]  _(put your own unikernel)_
- [ ] integrate `gilbraltar`/RPi4 (even if it's experimental, we did something which work) as a possible target

**Comment by samoht** [comment]
> fix bootvar for all targets 

This was already broken in MirageOS 3 so it's not a regression. It'd be nice to have consistent semantics for all the targets but this can be done in a later point release.
