### ISSUE TITLE
Release planning

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#1554]
Now that 4.7.0 is out, let's talk about 4.8.0. Likely in October. I propose the following issues to be fixed:
- [x] #1553 
- [x] #1552 
- [x] remove runtime_args_opt from devices/dns - make them non-optional, so we always have these runtime arguments in unikernels #1577 
- [x] remove runtime_args_opt from devices/git #1577 
- [x] remove runtime_args_opt from devices/happy_eyeballs #1577 
- [x] re-iterate on the ipv4/ipv6 no_init / ipv4_only/ipv6_only (avoid passing Runtime_keys around) #1577 
- [x] upgrade to mirage-crypto 1.0 (removes mirage-random, uses string instead of cstruct) #1559 
- [ ] defunctorise mirage-time & mirage-clock (and dependent changes) #1513 

Please add your thoughts as comments. Input is highly welcome.
