### ISSUE TITLE
2.5.0 release: TLS support

### ISSUE THREAD

**Issue by samoht** [mirage/mirage#409]
This is a summary of things to do before the release:
- [x] conduit, mirage-conduit, mirage-http and mirage releases in [mirage-dev](https://github.com/mirage/mirage-dev) (@samoht)
- [x] fix the memory leak in `mirage-net-unix` (@hannesm) (https://github.com/mirage/mirage-net-unix/pull/16)
- [x] fix mirage-www (@samoht) https://github.com/mirage/mirage-www/pull/317
- [x] fix the missing TCP state transition on simultaneous close for TCP (@yomimono and @balrajsingh)
- [x] satisfactory conclusion of #406.
- [x] explanation in the `CHANGES` file of how to adapt `config.ml` #415 
- [x] releases in `opam-repository` https://github.com/ocaml/opam-repository/pull/4211 (@samoht)
- [ ] blog posts: https://github.com/mirage/mirage-www/issues/320 (inc news release)

**Comment by samoht** [comment]
(And everyone should be happy with the status of #406)

**Comment by amirmc** [comment]
Dear all,

After a brief discussion with folks yesterday, I think we need to decouple aspects of the next set of MirageOS releases.  This is because we still have a small leak in the stack and although releasing is perfectly fine, it's not really something that should be immediately accompanied by a news release.

#### What happens now?

My thoughts are that we will do the following:

- We'll continue to work on and release software as we were planning to. e.g. @samoht will coordinate this and make decisions as appropriate, keeping everyone informed (i.e. what is already happening).
- We won't explicitly draw publicity/attention to the software releases.
- The software releases are independent of any upcoming talks (i.e. not tied or related to QConNYC)
- We'll wait until the minor leaks are *fixed* and *then* begin publishing the series of blog posts (they can still be drafted beforehand).
- At the end of the train of blog posts, we have the news release, via Xen Project and Linux Foundation. This allows the blog posts to be summarised and back-referenced in the news release itself.

From the quick discussions I had, this feels like the right way to do things and avoids anyone being blocked for too long.  Code can still be released, blogs/wikis can still be written and the news release can still be prepped (all mostly in parallel). 

The downside is that we won't have a concrete date for the announcement. However, we'll be able to trigger that review process as soon as we know that the relevant issues have been closed.  We're already tracking these on this issue.

#### Call to action!

- Get releases out!
- Squash bugs!
- Write posts/wiki pages!

Thanks folks! If you have comments or feedback on the above please do comment.

Amir

**Comment by amirmc** [comment]
I adjusted the order of the tasks in the list above and added an item for the issue in 406.

**Comment by avsm** [comment]
I added another note: we need to explain in the CHANGES how config.ml files should be adapted. My old ones no longer work with mirage-dev.

**Comment by samoht** [comment]
I've just release mirage-tcpip 2.5.0 in opam-repository

I've written some words for the CHANGES: https://github.com/samoht/mirage/commit/cc1ebfe0b1a399caf1b4eef4f2ca580930d67713

I've also fixed the removal of `zarith-xen` in https://github.com/ocaml/opam-repository/pull/4207

I'm almost ready to bulk release the contents of `mirage-dev` into `opam-repository`.

**Comment by samoht** [comment]
More boxes ticked. Almost there.

**Comment by amirmc** [comment]
:+1:

**Comment by samoht** [comment]
Last tickbox is checked. The remaining things to merge are https://github.com/mirage/mirage-skeleton/pull/95 and https://github.com/mirage/mirage-www/pull/334 which are waiting Travis CI to be able to download archive on the internet without blocking for 50 minutes.

**Comment by samoht** [comment]
ok, all the software are properly released. Now it's time to write blog posts to announce the release :-)

**Comment by samoht** [comment]
might also need a patch on mirage-deck, I'll check that

**Comment by amirmc** [comment]
Main post that notes the 2.5 changes is out so we can close this.
