### ISSUE TITLE
Fix support for disk images

### ISSUE THREAD

**Issue by samoht** [mirage/mirage#421]
The current support for disk images is not ideal. Crunch works great, but other backends (for instance `fat`) need some extra manual steps. Here a list of bugs:
- [ ] symbolic links are not added to the size of the file #420 
- [x] wrong device name #349 
- [ ] sub-directories in fat images are not added to the size of the file #422 
- [ ] add an option to not generate a fat file #423

**Comment by hannesm** [comment]
See #1353 - what about not generating disk images.
