### ISSUE TITLE
pending items for consideration for Mirage 3.0

### ISSUE THREAD

**Issue by yomimono** [mirage/mirage#571]
This issue intends to track ongoing work for the release of Mirage 3.0.  Also see #592. 
# mirage front-end tool
- [x] https://github.com/mirage/mirage/issues/499 - make it possible to specify package version constraints for unikernels. See also https://github.com/mirage/functoria/issues/54 and http://canopy.mirage.io/irclogs/29-06-2016 .   @hannesm started working on https://github.com/mirage/mirage/issues/392, see https://github.com/mirage/mirage/pull/691 and https://github.com/mirage/functoria/pull/82 
# mirage-types
- [x] https://github.com/mirage/mirage/issues/557 - rationalize ipv4 configuration, @yomimono .  See https://github.com/mirage/mirage/pulls/642 and https://github.com/mirage/mirage-tcpip/pull/643 and https://github.com/mirage/mirage-tcpip/pull/260 .
- [x] https://github.com/mirage/mirage/pull/551 - simplify the interface and implementation for random numbers. **_No PR**_ for implementation but @hannesm intends to work on this.
- [x] https://github.com/mirage/mirage-dev/pull/108 - remove type id from `DEVICE`.  PR by @talex5 could be merged and fallout worked through; @yomimono will do this in the absence of other volunteers.
- ~~`STACKV4` shouldn't expose `IPV4` or `ipv4`, and should be `STACK` instead. @yomimono is working on this.~~ This can be done independently of the release in `mirage-stack`.
- [x] https://github.com/mirage/mirage-dev/pull/107 - we could stand to have some better error types and reporting by requiring `pp_error` and use of `Result.result`.  @talex5 and @samoht have done work on this. @hannesm changed the error types for `V1.NETWORK` in https://github.com/mirage/mirage-dev/pull/166 and a framework for error printing.  @yomimono did some work on propagating errors through the network and storage stacks in a way that's useful for end users. @samoht has disaggregated the error/module type definitions so that each can be included and depended on separately.
- [x] https://github.com/mirage/mirage/issues/147 - `KV_RO` should have a `mem` function. **_No PR**_, but @yomimono has mentioned work in progress
- [x] https://github.com/mirage/mirage/issues/382 - rename `V1` module.  Involves  naming, one of the hardest problems in computer science.  See extensive discussion at http://canopy.mirage.io/irclogs/15-06-2016 , https://lists.xenproject.org/archives/html/mirageos-devel/2016-05/msg00019.html .  @yomimono is building a consistent universe with V1 -> Mirage_types, V1_LWT -> Mirage_types_lwt.  PR at https://github.com/mirage/mirage/pull/766 .
- [x] - move `mirage-types.lwt` to `mirage-types-lwt`.  @hannesm is working on a PR for this. see #670
## Other Libraries
- [x] ~~https://github.com/mirage/mirage-platform/issues/124 - move C bindings out of mirage-platform.  See also https://lists.xenproject.org/archives/html/mirageos-devel/2016-07/msg00044.html .  Will be easier once #568 is merged.~~ Retconned to be "make solo5 and non-solo5 libraries coinstallable on the same switch"

**Comment by hannesm** [comment]
(please feel free to add these to the task list and remove this comment:
- move C bindings out of mirage-platform https://github.com/mirage/mirage-platform/issues/124 (recent mailing list thread https://lists.xenproject.org/archives/html/mirageos-devel/2016-07/msg00044.html) -- will be easier once #568 is merged
- rename `V1` and `V1_LWT` to `M`/`M_LWT` (or `S`?) version-independent #382 and several mailing list & GitHub discussions
- `KV_RO` things (anybody volunteering?) #147 #149
- I guess #203 can be closed!?
- lots of block device stuff #421 
- deployment issues #517 #443

**Comment by yomimono** [comment]
Thanks @hannesm :) I have a branch for #147 but it got stalled on me being appalled by the general state of kv_ro.  Still, since someone cares I can PR it.

**Comment by yomimono** [comment]
@hannesm while the state of the block device is not great, I don't see anything in the high-level view from the issue at https://github.com/mirage/mirage/issues/421 that is API-breaking -- am I missing something?

**Comment by hannesm** [comment]
@yomimono I think you're right.  if we consider persistent storage to be important, we should have working examples in our configurations (crunch/fat/raw on unix&xen).  to me it feels like the current state is slightly broken (I do use crunch every now and then, and beware of size limits)

**Comment by hannesm** [comment]
it might be worth to go through all the libraries and fix `-safe-string` warnings (in the rise of https://github.com/ocaml/ocaml/pull/703 it even might improve performance -- my main motivation is correctness and fewer warnings)

**Comment by yomimono** [comment]
@avsm, is hannes's comment above something we could use the bulk builder for?  Getting a list of libraries that need investigation and how many warnings there are would be nice.

**Comment by samoht** [comment]
- tokpkg all the things!

**Comment by Drup** [comment]
> topkg all the things!

I realize I clearly don't have a say in this, but could you at least try to justify it ? Apparently I missed the memo. :)

**Comment by samoht** [comment]
@Drup we need a consistent way to release our 100s of packages. As far as I know, topkg is the only solution that I know which can make me handle my release quickly without much pain :-)

**Comment by Drup** [comment]
And you think it's worth the pain of using a crappy build description language such as pure ocamlbuild ? I can understand for functoria/mirage, those are simple projects (and even there, I don't find the ocamlbuild spaghetti satisfying, nor the extra build time dependency). But I'm slightly afraid of what's going to happen when you try to convert things like cohttp.

**Comment by mor1** [comment]
WRT the kv_ro things mentioned above, I'd like to add support to specify the directory target for `generic_kv_ro` (under the hood that means `crunch` etc) as a configuration time parameter. After conversation with @Drup the proper way to do this seems to be to change `generic_kv_ro` and friends to take a `string value` rather than a `string` directly -- more generally, to modify devices that take arguments `'a` to take `'a value` arguments instead. These would then be resolved in context at the relevant point in the device via something like `Key.eval (Info.context i) value`. This would be a fairly substantial API breaking change but would allow us to put all those hardcoded paths such as `"tls"` onto the command line as parameters where they (IMO :)) belong...

Thoughts?

/cc @Drup @samoht @yomimono @hannesm

**Comment by Drup** [comment]
To expand a bit on the benefit of taking `'a value` for parameters: it's much more flexible. It allows to take constants (as currently), user provided keys, but also values computed from (a set of) keys. Also, some devices (in particular the network ones) automatically create keys. This would allow to not do that, and allow to provide your own keys, which solves https://github.com/mirage/functoria/issues/35 (by avoiding the issue completely). Keys could still be created by default (yay optional arguments).

The immediate downside is that, if we change the API like that (and do not keep the old functions), people have to use `Key.pure` to provide constants (and they need to learn about the `value` type ...)

**Comment by amirmc** [comment]
I've added a section regarding announcements (blog posts, docs, news release).  I'll follow up with LF folks by email.

**Comment by hannesm** [comment]
curious - now that we have `connect` in some other shape, are we still heading to use `result` instead of the polyvars (`` [ `Ok of 'a | `Error of 'b ] ``) in mirage-types?  I think it would be worth doing (since we break APIs we can break them at once), but for sure needs someone to actually do it (can be done on one `module type` at a time basis).

**Comment by yomimono** [comment]
I'd still like to use `result` instead of the polyvars and include a `pp_error` in the `DEVICE` module type.  It'll be a lot easier to get working now that you've made the connect-time changes, I think.

**Comment by avsm** [comment]
result instead of polyvars would be great

**Comment by hannesm** [comment]
as noted here https://github.com/mirage/mirage/issues/203#issuecomment-48469221 it might be worth to keep the errors and pp_error outside of the module type (otherwise all implementations have to copy&paste the pp_error body)!?  using polyvars for errors, there could be one single big pp_error of all possible errors of all module types, implemented once.  but this would disallow module types to specify more errors (certainly each could specify a valid subset of the big polyvar)...

**Comment by hannesm** [comment]
instead of further discussion, I changed NETWORK to result type https://github.com/mirage/mirage-dev/pull/166

**Comment by hannesm** [comment]
now that error has been merged, and rename #766 is PR'ed, is there a schedule for the (beta) release?  and/or action items?

**Comment by yomimono** [comment]
Action item for me is figuring out why the pinned `lwt` no longer can install for tests, so I can verify that #766 isn't broken before merging.

@mato wanted to be around for the beta tagging and is away this week, so I've been planning on Monday for that work, and working on documentation this week.

**Comment by hannesm** [comment]
@yomimono sounds great to me.  I might have stumbled upon some regression -- after `mirage configure -t unix` I don't seem to be able to configure the logging level (`make` and `./foo -l *:debug' doesn't seem to work) -- anyone can reproduce this?

**Comment by yomimono** [comment]
All items here are now checked off.  Anyone looking for something to do is welcome to consult the larger issue list at https://github.com/mirage/mirage/issues/592 !  Thanks again to those who contributed here. :)
