### ISSUE TITLE
[tracking] docs.mirage.io

### ISSUE THREAD

**Issue by avsm** [mirage/mirage#609]
This is an experimental build of the unified documentation of MirageOS 3.0.  To push it to production, we need:
- [ ] a better front page (see dbuenzli/odig#7)
- [x] decide between ocamldoc and odoc (http://docs.mirage.io/odoc) which is incomplete but is the future tool that supports cross referencing among packages.  Ideally we would use odoc but it may not be ready in time.
- [x] port more libraries over to obey the odig convention so that the `changes` `license` and `readme` commands all work.  (see dbuenzli/odig#8)
- [x] add a full breadcrumb trail across packages (dbuenzli/odig#11)
- [x] support ppx in interface files (dbuenzli/odig#12) : release note this as a limitation in ocamldoc -- if we switch to odoc then everything works fine.
- [x] broken links for CHANGES/README links (dbuenzli/odig#13)

Rendering artefacts for odoc vs ocamldoc:
- [ ] Omd: ocaml-doc/odoc#30
- [ ] ocaml-doc/doc-ock-html#7
- [ ] https://github.com/ocaml-doc/odoc/issues/33

**Comment by yomimono** [comment]
Do I understand correctly that using `odoc` would let us surface things like "which  libraries have modules that include `Mirage.V1.KV_RO` in their signature" ?  It's a bit niche but I want to answer questions like this fairly frequently.

**Comment by avsm** [comment]
From @mato on mirageos-devel and my comments inline:

> 1) Hyperlinks on types. Eg. in functoria/Functoria_app.Cmd.html
"Rresult.result" should link to rresult/Rresult.html.

This is taken care of in the experimental "odoc" mode: http://docs.mirage.io/odoc, see for example http://docs.mirage.io/odoc/functoria/Functoria_app/Cmd/index.html which does link to Rresult :)
 
> 2) A "Path" nagivation header with the full hierarchy. E.g. rresult/Result.html currently has "Up", which takes me to the package's index.page but I can't go "Up" from there.

Filed in dbuenzli/odig#11

> 3) A "Search" box of some sort. Ideally just client-side, search over packages/modules/types/descriptions?

Not clear where this belongs yet.  @dbuenzli -- do you see this in scope for odig, or a separate tool like Merlin?

**Comment by dbuenzli** [comment]
> Not clear where this belongs yet. @dbuenzli -- do you see this in scope for odig, or a separate tool like Merlin?

Not sure if it's that useful. You can use your webbrowser page search on a given page or consult one of the indices and use your webbrowser page search on these. I'd rather add full-text documentation search at some point.

**Comment by hannesm** [comment]
a potential solution for the search box may be a custom instance of https://github.com/camlspotter/ocamloscope.2 (as mentioned on mirageos-devel, tracking it here so it does not get lost)

**Comment by avsm** [comment]
Also added dbuenzli/odig#12 to the list as a number of packages on docs.mirage.io seem to error if they expose ppx extensions in their MLIs

**Comment by dbuenzli** [comment]
I closed it because the problem cannot be solved on the `ocamldoc` path.

**Comment by hannesm** [comment]
odoc output: no line breaks in sum types (see http://docs.mirage.io/odoc/tls/Config/index.html#/own_cert.typ), fields of record types are not indented (see http://docs.mirage.io/odoc/tls/Config/index.html#/config.typ)

**Comment by dbuenzli** [comment]
@hannesm I don't think it's worth reporting `odoc` problems here. There are many known problems and they are tracked in odoc's issue tracker (in this case https://github.com/ocaml-doc/odoc/issues/19), I don't think it's useful to report anything before @trefis makes a first big round on these.

**Comment by avsm** [comment]
Thanks, I wasn't sure where to report them either in ocaml-doc, so that issue link is helpful.

**Comment by dbuenzli** [comment]
@avsm We decided with @trefis and @lpw25 that we report everything in the `odoc` tracker and label appropriately.

**Comment by hannesm** [comment]
@dbuenzli ic. sorry for the noise.

**Comment by avsm** [comment]
Switched over to odoc by default in https://github.com/mirage/mirage/pull/741 and reported a rendering issue in https://github.com/mirage/mirage/pull/741

**Comment by dbuenzli** [comment]
It seems I can no longer access the `ocamldoc` documentation. That was useful to highlight discrepancies to `odoc` devs. I also wouldn't have switched to `odoc` as the default before the next iteration.

**Comment by avsm** [comment]
More packages seem to be broken on ocamldoc than not, thanks to ppx.  I've put the ocamldoc output on http://docs.mirage.io/ocamldoc_/ instead now.

**Comment by avsm** [comment]
CHANGES links introduced in #765

**Comment by dbuenzli** [comment]
And ocamldoc now on http://docs.mirage.io/_ocamldoc

**Comment by hannesm** [comment]
@avsm can docs.mirage.io generate documentation of released libraries now (i.e. those in opam-repository)?

**Comment by yomimono** [comment]
[docs.mirage.io](http://docs.mirage.io/) is live and has been for some time.  I think the list of TODOs here is pretty bitrotted and largely about other repositories, so I'll close this issue.  If you disagree please feel free to reopen. :)
