### ISSUE TITLE
[tracking] Mirage 3.2.0 release

### ISSUE THREAD

**Issue by mato** [mirage/mirage#923]
This issue is to track the steps towards a Mirage 3.2.0 release.

## Solo5 changes

As of Solo5 0.4.0 (to be released in the next few days), the Solo5 OPAM packages and `ukvm` target have been renamed to `hvt`. The following needs to be done for a release:

1. [ ] ocaml/opam-repository#12612 needs to land _and_ show up in the public repositories (@mato).
2. [ ] Solo5 0.4.0 changes are completed and an 0.4.0 release is published. (@mato, Solo5/Solo5#274)
3. [ ] Downstream MirageOS dependencies get new 0.4.0 releases (`ocaml-freestanding`, `mirage-solo5`). These changes are straightforward and I have them ready on WIP branches. (@mato)
4. [ ] The required `mirage` frontend changes are reviewed and merged. (WIP: https://github.com/mato/mirage/tree/wip-renaming, @mato + reviewers)
5. [ ] Sundry updates, such as `.travis.yml` and/or other CI scripts for `mirage/mirage-skeleton`.
6. [ ] MirageOS documentation needs to be updated.

@mirage/core I'd appreciate it if someone could volunteer to work on steps 4 through 6 above.

## Other changes

@hannesm Please edit and add, these are mainly the `tcpip` API changes?

**Comment by mato** [comment]
Notes on upgrading an existing Mirage/Solo5 switch to one based on Mirage 3.2.0 (to be added to `CHANGES.md` and/or part of the release announcement:

----

## Upgrading from Mirage 3.1.x or earlier

Due to conflicting packages, `opam` will not upgrade `mirage` to version _3.2.0_ or newer if a version of `mirage-solo5` older than _0.4.0_ is installed in the switch. To perform the upgrade you must run:

    opam upgrade mirage

explicitly. After the upgrade has completed, you may want to verify that the correct `solo5-bindings-*` package was installed. (_Unclear if to refer to this, I just get solo5-kernel-ukvm replaced with solo5-bindings-hvt. `make depend` should do the right thing anyway._)

## Changes required to rebuild and run `ukvm` unikernels

As of Solo5 0.4.0, the `ukvm` target has been renamed to `hvt`. If you are working out of an existing, **dirty**, source tree, you should initially run:

    mirage configure -t hvt
    mirage clean
    mirage configure -t hvt

and then proceed as normal. If you are working with a **clean** source tree, then simply configuring with the new `hvt` target is sufficient:

    mirage configure -t hvt

Note that the build products have changed:

1. The unikernel binary is now named `<unikernel>.hvt`,
2. the `ukvm-bin` binary is now named `solo5-hvt`.

**Comment by mato** [comment]
Note that I will add a `post-message` to `mirage-solo5.0.4.0` referring to these changes. This should point to a URL, presumably    https://github.com/mirage/mirage/blob/master/CHANGES.md will do for now?

**Comment by hannesm** [comment]
@mato could you open a PR on this repository with your changes? thanks!

**Comment by mato** [comment]
@hannesm Should I add the `conflicts: [ ... "mirage-solo5" {>= "0.4.0"} ]` to `mirage.opam` on current master ASAP to prevent any accidental CI failures while the intermediate steps in this issue are completed and before #924 is merged?

**Comment by hannesm** [comment]
@mato sounds good to me.

**Comment by hannesm** [comment]
Update: I cherry-picked #924 into #920, and adjusted travis-ci.sh to use https://github.com/mirage/mirage-skeleton/pull/260 (and tcpip/mirage/mirage-runtime/mirage-types/mirage-types-lwt/charrua-client-mirage/mirage-qubes-ipv4 from https://github.com/mirage/mirage-dev (which points to my git repos on the less-types branches)) - the resulting run is successful: it can compile mirage-skeleton in this new universe.

**Comment by hannesm** [comment]
what is left to do: prepare changes / release announcement and get #920 merged (as well as https://github.com/mirage/mirage-skeleton/pull/260 and maybe other CI modifications which still reference `ukvm`).  anyone up for reviewing #920 (which includes #924)?  I can work on the CHANGES this evening.

**Comment by hannesm** [comment]
FWIW, some critique on the backwards compatibility: while we managed to have `mirage clean` remove `*ukvm.opam` and `_build-ukvm`, which sounds like a great idea; the reality is slightly different. If there's a directory where `mirage configure -t ukvm` has been run (using an earlier mirage release), and `mirage build` was done in the same directory (e.g. it is dirty now), upgrading `mirage` will result in a mirage that complains on every command (`build`, `clean`, etc.) apart from `configure` -- the reason is that the configured unikernel is no longer a valid configuration (since `-t ukvm` is unknown).

This left me with a bunch of directories where the solution was to run `mirage configure -t hvt` followed by `mirage clean` (crucial, otherwise the `_build` directory is kept), and `mirage configure -t hvt` again, in order to `mirage build` this unikernel.

IMHO this is just a minor issue, but I wanted to document it for the case that someone else hits such an issue (and/or for future MirageOS development -- unclear to me whether we want to gracefully deal with such situations or not). From a UX 3.2.0 was pretty bad to me.

**Comment by mato** [comment]
@hannesm Unfortunately, yes, that's how it works. W/o having `mirage clean` remove the old ukvm build products even that would not work, since you'd get hygiene errors on the subsequent `mirage build`.

But yeah, in hindsight we should have probably kept `-t ukvm` as a "valid" value for 3.2.0.
