### ISSUE TITLE
release 3.3.0

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage#939]
@mirage/core I plan to do a Mirage release this week - please let me know if you'd like to include one or the other outstanding PR (feedback and merging/approving PRs is welcome as well) - noteworthy changes:
   - [x] introducing mirage-bootvar-unix #931 (unified semantics for boot arguments across all (not entirely sure, at least virtio, unix, hvt, likely xen) targets!)
   - [x] mirage-random-stdlib: new opam package that provides a properly seeded Random module (used to be part of mirage-random, is no longer) -- not to be used directly (instead, use mirage utility and the Mirage_random.C interface) :)
   - [x] the OS module no longer includes an `Env` module (used to be used on Unix to retrieve argv, now via mirage-bootvar-unix)
   - [x] segregation into `_impl` modules #933
   - [x] nicer backwards-compatible handling of `-t ukvm` #937
   - [x] move to dune #927
   - [x] opam2 output #926 #936
   - [x] charrua-client uses the old Mirage_random.Stdlibrandom which is no longer existing, see https://github.com/mirage/charrua-core/pull/87
   - [x] Dhcp_client now needs the Random explicitly #938
   - [x] remove io_page configuration #940
   - [x] generate upper bounds #946 
   - [x] mirage-tcpip (uses Stdlibrandom in tests) https://github.com/mirage/mirage-tcpip/pull/377
   - [x] Mirage/Solo5: fix handling of Cstruct buffer offset in block/net stubs (mirage/mirage-solo5#37)
   - [x] Native Genode target (#942)

to stage these changes:
   - [x] old mirage-os-shim won't be happy with old mirage-{xen,unix,solo5} (due to "missing" OS.Env module), I'll need to put some upper bounds
   - [x] old mirage versions will use Mirage_unix.OS.Env.argv, need to conflict with newer mirage-unix
   - [x] old mirage versions will use Mirage_random.Stdlibrandom for randomness  ~~I plan to add upper bounds of mirage-random in existing mirage-types{-lwt?}~~, conflict with newer mirage-random
   - [x] opam-repository PR introducing upper bounds at https://github.com/ocaml/opam-repository/pull/12937
   - [x] opam repository PR introducing upper bounds in tcpip for mirage-random https://github.com/ocaml/opam-repository/pull/12941
   - [x] Solo5 upper bounds in OPAM ocaml/opam-repository#12944

releases required:
- [x] mirage 3.3.0, mirage-runtime 3.3.0, mirage-types.3.3.0, mirage-types-lwt.3.3.0
- [x] charrua 0.11.0 (PR https://github.com/ocaml/opam-repository/pull/12995)
- [x] functoria 2.2.2 (PR https://github.com/ocaml/opam-repository/pull/12996)
- [x] mirage-random 1.2.0 (PR https://github.com/ocaml/opam-repository/pull/12965)
- [x] mirage-random-test 0.0.1 (PR https://github.com/ocaml/opam-repository/pull/12952)
- [x] mirage-os-shim 3.1.0 (PR https://github.com/ocaml/opam-repository/pull/12964)
- [x] mirage-xen 3.1.0 (PR https://github.com/ocaml/opam-repository/pull/12967)
- [x] mirage-unix 3.1.0 (PR https://github.com/ocaml/opam-repository/pull/12966)
- [x] tcpip 3.5.1 (PR https://github.com/ocaml/opam-repository/pull/12993)
- [x] Solo5 packages (PR ocaml/opam-repository#12950)
   - solo5-bindings-{hvt,virtio,muen,genode}.0.4.1
   - ocaml-freestanding.0.4.2
   - mirage-solo5 0.5.0
   - mirage-block-solo5.0.4.0
   - mirage-net-solo5.0.4.0

**Comment by mato** [comment]
@hannesm Your list looks good. A couple of comments:

1. The change introducing `mirage-bootvar-unix` will potentially change the semantics of passing command line arguments. Given that these are not and have never been documented anywhere and are still "in flux" (see mirage/parse-argv#6), I'm not proposing to document them now, but at least verify that the tutorials on the website work as advertised and update them to the 3.2.1 semantics if not.
2. Given that we need a release of `mirage-solo5` here anyway, I should finish and PR the bigarray-related fixes identified/developed at the retreat as part of getting Wodan to work (https://github.com/mato/camel-service) since these also need a new `mirage-solo5`. So, if you don't mind waiting a couple of days for that to happen, I think it'd been good to do now rather than later.

**Comment by hannesm** [comment]
@mato agreed with both points. And thanks for replying.  The purpose of this tracking issue is as well to get some feedback whether others have outstanding PRs (@emillon @samoht) to any packages which should be merged before a release.

FWIW, I plan to:
- adjust the upper bounds and conflicts in opam-repository (soon)
- stage all the to-be-released libraries in the `mirage-dev` repository (also soon, maybe tonight)
- if and only if the staging repository works fine with mirage-skeleton, draft releases

the current CI failures https://github.com/ocaml/ocaml-ci-scripts/issues/265 may actually block all of this work (apart from my limited time.
I'd appreciate PR feedback esp. on charrua:
- https://github.com/mirage/charrua-core/pull/87 @haesbaert @yomimono)
- a `rawlink` release would be great to have before a mirage release (@haesbaert https://github.com/haesbaert/rawlink/pull/10)
- rawlink breaks API and needs a minor commit to charrua (https://github.com/mirage/charrua-core/pull/82/commits/ea69976a87403511280a019e984c464613515c68)

**Comment by hannesm** [comment]
I decided on some version numbers above and introduced conflicts in the opam-repository.

Versioning and conflicts are a bit intricate at the moment:
 - The mirage utility generates code that requires a certain package, with appropriate lower bounds.
 - Once we change the interface of that package, we bump the lower bound in the new mirage utility.
 - We conflict old releases of mirage with the newer package.
 - This is slightly insufficient: the configured MirageOS unikernels on any hard drive (with an old mirage) are attempted to be build with the newer package if you run opam update and opam upgrade in between mirage configure and make.

To fix this properly in the future, I think we need to revive https://github.com/mirage/mirage/pull/855. This should IMHO be part of the next mirage release.

**Comment by hannesm** [comment]
@mato agreed that we need to give consideration in respect to upper bounds (e.g. charrua uses atm 0.x versioning, which we should streamline with other mirage projects). I'm in favour of waiting for #855 for _this_ release (3.2.1), and proactively put it into the task list above. For the generated `mirage-types*` dependency, I'd be in favour of using `>= 3.x.y & < 3.(x + 1).0` - which allows us to break interfaces on every minor version.

NB: the mirage-dev repository successfully built the 3.2.1 package universe :)

**Comment by mato** [comment]
N.B. I've added the Mirage/Solo5 bits to the task list in the description.

**Comment by mato** [comment]
@hannesm Can you please change the `solo5-bindings-*` upper bounds in #855 (or wherever your "current" copy of this is) to `{>="0.4.0" & <"0.6.0"}`. I'd like to call the upcoming Solo5 release 0.5.0 rather than 0.4.x since the Genode bindings are new functionality.

**Comment by hannesm** [comment]
@ehmry @mato I enabled a `MODE=genode` run on [travis in mirage-dev](https://travis-ci.org/mirage/mirage-dev/jobs/454146051), and get the following failure:
```
mirage: [WARNING] pkg-config solo5-bindings-genode --variable=ld returned nothing, using ld
ld: /home/travis/.opam/ocaml-base-compiler.4.06.1/lib/pkgconfig/../../lib/ocaml-freestanding/libasmrun.a(amd64.o): relocation R_X86_64_PC32 against symbol `caml_last_return_address' can not be used when making a shared object; recompile with -fPIC
ld: final link failed: Bad value
```

any idea what is wrong?

**Comment by ehmry** [comment]
I think the linker is working fine here, but the `-fPIC` flag didn't propagate through pkg-config to ocaml-freestanding...

**Comment by emillon** [comment]
> The purpose of this tracking issue is as well to get some feedback whether others have outstanding PRs

FTR, my open PRs are not tied to the interface, so they can wait after the release. Thanks!

**Comment by mato** [comment]
@hannesm @ehmry I don't get this error when building on Debian stable. I suspect that this may be an issue with the Ubuntu Trusty toolchain that is being used on Travis.

@hannesm Can you try bumping the Travis environment(s) to use Ubuntu Xenial and see if the problem goes away? This should be just adding `dist: xenial` to the configuration and removing the `UPDATE_GCC_BINUTILS=1`.

@ehmry Having said that, looking at the Genode build products I see on Debian they don't look entirely correct. I'll ping you separately about this and discuss somewhere else so as not to bother everyone else here with the noise.

**Comment by ehmry** [comment]
I created a script of instructions for testing a Mirage image: https://gist.github.com/ehmry/ab83d8eecfbaa1fc93725592a487daff

If there are any issues or discussions, please take them to #mirage or #genode on freenode, or contact me directly.

**Comment by hannesm** [comment]
@mato tried with `xenial`, same issue at https://travis-ci.org/mirage/mirage-dev/jobs/455222600

**Comment by mato** [comment]
On Wednesday, 14.11.2018 at 14:52, Hannes Mehnert wrote:
> @mato tried with `xenial`, same issue at https://travis-ci.org/mirage/mirage-dev/jobs/455222600

I can have a look at this next week, no idea what's going on. Would have to
try and reproduce in a xenial container or similar.

-mato

**Comment by hannesm** [comment]
I just released tcpip 3.5.1 :D

instead of releasing mirage 3.3.0 now, I plan to wait until the following are merged (+released):
- [ ] https://github.com/mirage/functoria/pull/163
- [ ] https://github.com/mirage/functoria/pull/151
- [ ] #946 
- [ ] #948 
- [ ] charrua 0.11 release (PRs are merged now into charrua, i can cut a release)

**Comment by hannesm** [comment]
now PRed to opam-repository https://github.com/ocaml/opam-repository/pull/13001
